### ISSUE TITLE
Iternal compiler Error

### ISSUE THREAD

**Issue by ztzhang** [zgimbutas/fmmlib3d#3]
Hi, I've been trying to compile the fortran code but constantly hitting internal compiler error using gcc 6.3.0

Would it  be possible for you to share a working gcc version for compilation? 

Thanks!

**Comment by zgimbutas** [comment]
This is somewhat unusual, you most likely hit an internal compiler bug in
certain OS+toolchain+gcc configuration.

On Linux CentOS 7, I was able to successfully run library tests, both 'make
test' and 'make test-openmp', with gcc-4.8.5, gcc-5.5.0, gcc-6.4.0, and
gcc-7.2.0.

**Comment by zgimbutas** [comment]
What is your operating system? Do you see the internal compiler error while
running 'make test'?

**Comment by ztzhang** [comment]
Hi,
Thanks for your prompt reply!

Just as you said, the problem is on my side: 

I've been able to compile it on a different machine running the same version of OS(Ubuntu 14.04.5) and GCC 6.3.0(shared via NFS, so exactly the same build).

And yes, for that machine, I hit ICE for all the make options except for the mwrap. 

I'm still tracing the problem. Thanks for the help!
