### ISSUE TITLE
Loss of accuracy when compiled with `-march=native`

### ISSUE THREAD

**Issue by mattwala** [zgimbutas/fmmlib3d#4]
I'm using pyfmmlib as a frontend. The following code evaluates a 3D Laplace potential with 1000 random sources:

```python
import numpy as np
import numpy.linalg as la


def main():
    dims = 3
    np.random.seed(10)
    sources = np.random.randn(1000, dims)

    from pyfmmlib import LaplaceKernel, fmm_part
    pot = fmm_part("p", iprec=1, kernel=LaplaceKernel(), sources=sources, mop_charge=1)
    print(np.max(np.abs(pot - ref_pot(sources))))


def ref_pot(sources):
    distvecs = sources.T.reshape(3, 1, -1) - sources.T.reshape(3, -1, 1)
    dists = np.sqrt(np.sum(distvecs ** 2, axis=0))
    invdists = np.zeros_like(dists)
    np.divide(1, dists, out=invdists, where=(1 - np.eye(1000, dtype=int)).astype(np.bool))
    return np.sum(invdists, axis=1) / (4 * np.pi)


if __name__ == "__main__":
    main()
```

When I run this using pyfmmlib/fmmlib with the default compile args, I get the error
```
1.959857890199146e-06
```

When I add `-march=native` as a compiler argument, I get the error
```
1.527760927415783
```

I'm using gfortran 8.2 and I'm running on an Intel Xeon E5-2650 v3 machine. [Here's](
https://gist.github.com/mattwala/b4587502d72f10d5cb62c9d4c03eba01) the list of compile flags that `-march=native` enables on the machine.

I'm also seeing similar losses of accuracy using boxtree's fmmlib-backed FMM implementation, with both Helmholtz and Laplace kernels.

cc: @inducer

**Comment by zgimbutas** [comment]
Hi Matt,

I was not able to replicate this error on my machine (I don’t have your configuration and am using macOS + gfortran 7.2.0 on MacBook Pro 2015, Haswell) with the above flag. 

It could be either a compiler bug or some strange list processing bug in the code. Would it be possible to test the Fortran libraries from the most recent fmmlib3d develop branch? Does it happen with both gfortran 7.2 and 8.2 on your machine? Can the bug be activated with different number of charges?

Zydrunas

**Comment by mattwala** [comment]
Hi Zydrunas:

The recent development branch appears to have the same problems. When I use gfortran 7.2, I don't appear to get this issue, so I believe this issue has to do with recent changes to the compiler (but I haven't tried 8.1). I get this problem with as few as 800 sources. I think there could be source / iprec configurations that would lead to errors with fewer charges.

Additionally, I'm using pyfmmlib's build process rather than the fmmlib makefiles. I think it uses the following full set of compiler flags. I forgot to specify these.
```
gfortran -Wall -g -ffixed-form -fno-second-underscore -fPIC -O3 -funroll-loops -std=legacy -march=native
```

**Comment by zgimbutas** [comment]
Hi Matt, 

There seems to be something wrong with -march=native flag in gcc8 (google: gcc 8.2 phoronix).  Have you tried flags like -march=corei7-avx or -march=corei7-avx2, or omitting the -march flag all together?

I will try to install gcc8 on my workstation today and will  check if I can reproduce the bug.

**Comment by mattwala** [comment]
Hi Zydrunas:

When I remove the `march` flags, there isn't a problem. `march=corei7-avx`, `march=core-avx2`, and `march=haswell` all seem to show the problem. 

Additionally, I tried running this on a 2015 Macbook, and I can reproduce the issue there with the flags `-O3 -march=corei7-avx`.

**Comment by zgimbutas** [comment]
Thanks for this info. On my machine (Sandy Bridge Intel(R) Xeon(R) CPU
E5-2687W 0 @ 3.10GHz), I replicated the bug with

make -f lfmm3dpart.make HOST=linux-gfortran FFLAGS="-O3 -march=corei7-avx"
-j
make -f lfmm3dpart.make HOST=linux-gfortran FFLAGS="-O2
-ftree-loop-vectorize -march=corei7-avx" -j

while this works correctly:

make -f lfmm3dpart.make HOST=linux-gfortran FFLAGS="-O2 -march=corei7-avx"
-j
make -f lfmm3dpart.make HOST=linux-gfortran FFLAGS="-O3 -march=corei7" -j

I used gcc 8.2.0 documentation from

https://gcc.gnu.org/onlinedocs/gcc-8.2.0/gcc/Optimize-Options.html#Optimize-Options

and checked all possible offending options for -O3.

It would appear that the combination of flags '-ftree-loop-vectorize
-march=corei7-avx' breaks the optimizer in gcc 8.2.0

I have no idea what -ftree-loop-vectorize does. It might be possible to see
exactly which part of the code breaks by printing out intermediary results.
The tree generation seems to be correct though.

Right now, I suspect that you simply hit an optimizer bug for generating
the AVX floating point code.

**Comment by mattwala** [comment]
Thanks for taking a look! I will avoid that flag for now.

**Comment by zgimbutas** [comment]
A similar issue with aggressive gfortran optimizer flags may occur in Flatiron FMM3D. Reopening, with some hope that a workaround will be found.

**Comment by ahbarnett** [comment]
in my experience GCC 8 is a disaster - use 7 or 9 - wonder if persists then?

**Comment by zgimbutas** [comment]
GCC 9 is not much better with random issues while using -march=skylake-avx512. I also had to deal with optimizer bugs in handling archaic declarations such like real *8 a(1) (ok, I know it should be real *8 a(*), but still, it is a nuisance). Since Ubuntu 20.04LTS has defaulted to GCC 9, we will unfortunately have to live with mildly unstable compiler environments. I have no idea what is going to happen when we switch to GCC/GFORTRAN  10, but my first impression while using this compiler is that we will need to use -std=legacy just to compile our codes, because simple basic codes like prini.f give compiler errors.

**Comment by inducer** [comment]
I think it might be worth tracking down what set of expressions is causing this and reporting that upstream. That way, it'll become part of their regression tests and is unlikely to cause problems in the future.
